"""Initial migration 1 

Revision ID: 2529e555a2f8
Revises: 
Create Date: 2024-09-12 18:59:56.280084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2529e555a2f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('ci')
    )
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('ci_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ci_usuario'], ['usuarios.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.Column('ci_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ci_usuario'], ['usuarios.ci'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacciones')
    op.drop_table('cuentas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
