"""Initial migration

Revision ID: 751dc8aacdbf
Revises: 
Create Date: 2024-09-04 13:45:59.787139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751dc8aacdbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('ci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
