"""migracion 2 

Revision ID: d1d65ea40aa5
Revises: bb272aa8de0a
Create Date: 2024-09-11 22:38:20.483780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d65ea40aa5'
down_revision = 'bb272aa8de0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Integer(), nullable=False))
        batch_op.alter_column('monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
