"""Regenerar m

Revision ID: dcf5011af329
Revises: e8949f95253f
Create Date: 2024-09-10 20:15:28.159502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf5011af329'
down_revision = 'e8949f95253f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ci_usuario', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['ci_usuario'], ['ci'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ci_usuario')

    # ### end Alembic commands ###
